/**
 * Claude Code Command Template Generator
 *
 * Generates a .claude/commands/ file that integrates with GitHub Task Kit
 */

/**
 * Generate Claude Code command file content
 */
export function generateClaudeCommand(config) {
  const { owner, repo, projectNumber, projectId, fieldIds, statusOptions } = config;

  return `---
description: Create tracked GitHub issue with comprehensive metadata and codebase analysis
type: project
complexity: medium
model: claude-sonnet-4-5-20250929
---

# GitHub Create Task
# QUICK: Create comprehensive GitHub issue with rich documentation

Create a fully documented GitHub issue with codebase analysis, references, and testing workflow.

## Overview

This command creates a comprehensive, well-documented GitHub issue with:
- Detailed problem statement and acceptance criteria
- Automatic codebase analysis with file/line references
- Reference documentation links
- Recommended approach with todo checklist

**Project**: ${owner}/${repo} (Project #${projectNumber})

---

## Configuration

\`\`\`yaml
# Auto-generated by GitHub Task Kit
project_board:
  owner: "${owner}"
  repo: "${repo}"
  project_number: ${projectNumber}
  project_id: "${projectId}"

field_ids:
  status: "${fieldIds?.status || 'CONFIGURE_ME'}"
  priority: "${fieldIds?.priority || 'CONFIGURE_ME'}"
  qa: "${fieldIds?.qa || ''}"

status_options:
  todo: "${statusOptions?.todo || 'CONFIGURE_ME'}"
  in_progress: "${statusOptions?.in_progress || 'CONFIGURE_ME'}"
  done: "${statusOptions?.done || 'CONFIGURE_ME'}"
\`\`\`

---

## Workflow

### PHASE 1: Gather Information

Use AskUserQuestion to collect:

1. **Issue Title** - Clear, concise description
2. **Issue Description** - Problem statement, expected vs actual behavior
3. **Labels** - Type (bug, feature, refactor), Stack (frontend, backend)
4. **Priority** - P0-Critical, P1-High, P2-Medium, P3-Low

### PHASE 2: Codebase Analysis

**Deploy Explore Agent** to gather:

1. Find relevant files matching the issue domain
2. Locate key functions with line numbers
3. Identify patterns to follow
4. Gather code snippets

### PHASE 3: Create Issue

\`\`\`bash
# Create the issue
ISSUE_URL=$(gh issue create --repo ${owner}/${repo} \\
  --title "[TITLE]" \\
  --body "[GENERATED_BODY]" \\
  --label "[LABELS]" \\
  --assignee "${owner}")

# Extract issue number
ISSUE_NUM=$(echo "$ISSUE_URL" | grep -oP '\\d+$')

# Add to project board
gh project item-add ${projectNumber} --owner ${owner} --url "$ISSUE_URL"

echo "Created: Issue #$ISSUE_NUM"
echo "URL: $ISSUE_URL"
\`\`\`

### PHASE 4: Update Project Board Fields

\`\`\`bash
# Get item ID
ITEM_ID=$(gh project item-list ${projectNumber} --owner ${owner} --format json | jq -r ".items[] | select(.content.number == $ISSUE_NUM) | .id")

# Set Status to Todo
gh project item-edit --id "$ITEM_ID" \\
  --field-id ${fieldIds?.status || 'STATUS_FIELD_ID'} \\
  --project-id ${projectId} \\
  --single-select-option-id "${statusOptions?.todo || 'TODO_OPTION_ID'}"

# Set Priority (if field exists)
# gh project item-edit --id "$ITEM_ID" \\
#   --field-id ${fieldIds?.priority || 'PRIORITY_FIELD_ID'} \\
#   --project-id ${projectId} \\
#   --single-select-option-id "[PRIORITY_OPTION_ID]"
\`\`\`

---

## Issue Body Template

The generated issue body includes:

\`\`\`markdown
## Problem Statement

[Clear description of the issue]

## Expected vs Actual Behavior

**Expected**: [What should happen]
**Actual**: [What currently happens]

## Acceptance Criteria

- [ ] Criterion 1
- [ ] Criterion 2

---

## Code Analysis

### Relevant Files & Functions

| File | Line | Function/Component | Purpose |
|------|------|-------------------|---------|
| [file] | [line] | [function] | [purpose] |

### Patterns to Follow

- [Pattern from codebase analysis]

---

## Recommended Approach

### Todo List

- [ ] **Step 1**: [Task]
- [ ] **Step 2**: [Task]

---

*Created by GitHub Task Kit*
\`\`\`

---

## Labels Reference

**Type**:
- \`bug\` - Something isn't working
- \`feature\` - New functionality
- \`feature-update\` - Enhancement to existing feature
- \`refactor\` - Code improvement without behavior change
- \`documentation\` - Documentation only

**Stack**:
- \`frontend\` - UI/client changes
- \`backend\` - API/server changes

**Priority**:
- \`P0-Critical\` - Production broken
- \`P1-High\` - Major feature affected
- \`P2-Medium\` - Minor bug or new feature
- \`P3-Low\` - Nice to have

---

## Quick Commands

\`\`\`bash
# After creating issue, start working
git pull origin main

# When done
git add -A
git commit -m "feat: [description] (#[NUM])"
git push origin main
\`\`\`

---

## See Also

- \`gh issue list --repo ${owner}/${repo}\` - List issues
- \`gh project view ${projectNumber} --owner ${owner}\` - View project board

---

*Generated by GitHub Task Kit - https://github.com/yourname/github-task-kit*
`;
}

/**
 * Generate minimal Claude command (just the essentials)
 */
export function generateMinimalClaudeCommand(config) {
  const { owner, repo, projectNumber } = config;

  return `---
description: Create GitHub issue for ${repo}
type: project
---

# Create Task

Quick issue creation for ${owner}/${repo}.

## Usage

1. Provide title and description
2. Select labels and priority
3. Issue created and added to project #${projectNumber}

## Command

\`\`\`bash
gh issue create --repo ${owner}/${repo} --title "[TITLE]" --body "[BODY]"
gh project item-add ${projectNumber} --owner ${owner} --url "[ISSUE_URL]"
\`\`\`
`;
}
