/**
 * Template Generation
 *
 * Generates command templates and testing rules from tech stack configuration.
 *
 * Provides:
 * - generateCommandTemplates: Create .claude command templates
 * - generateTestingRules: Generate TESTING_RULES.md from tech stack
 */

import ora from 'ora';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';

/**
 * Generate command templates
 */
export async function generateCommandTemplates(projectRoot, techStack) {
  const spinner = ora('Generating command templates...').start();

  const commandsDir = join(projectRoot, '.claude', 'commands');
  if (!existsSync(commandsDir)) {
    mkdirSync(commandsDir, { recursive: true });
  }

  // Generate TESTING_RULES.md
  const testingRulesContent = generateTestingRules(techStack);
  writeFileSync(
    join(projectRoot, '.claude', 'task-lists', 'TESTING_RULES.md'),
    testingRulesContent,
    'utf8'
  );

  // Ensure task-lists dir exists
  const taskListsDir = join(projectRoot, '.claude', 'task-lists');
  if (!existsSync(taskListsDir)) {
    mkdirSync(taskListsDir, { recursive: true });
  }
  writeFileSync(
    join(taskListsDir, 'TESTING_RULES.md'),
    testingRulesContent,
    'utf8'
  );

  spinner.succeed('Command templates generated');
  console.log(chalk.green('  ✓ .claude/task-lists/TESTING_RULES.md'));
}

/**
 * Generate TESTING_RULES.md from tech stack
 */
function generateTestingRules(techStack) {
  const tunnelUrl = techStack.urls?.tunnel?.frontend || '{{TUNNEL_URL}}';
  const prodUrl = techStack.urls?.production?.frontend || '{{PRODUCTION_URL}}';
  const backendUrl = techStack.urls?.production?.backend || '{{BACKEND_URL}}';
  const selectors = techStack.testing?.selectors || {};

  return `# Testing Rules (Auto-Generated)

## Environment URLs

| Environment | Frontend | Backend |
|-------------|----------|---------|
| Local | http://localhost:${techStack.frontend?.port || 5173} | http://localhost:${techStack.backend?.port || 8000} |
| Tunnel | ${tunnelUrl} | ${tunnelUrl} |
| Production | ${prodUrl} | ${backendUrl} |

## Login Credentials

- **Username Variable**: \`${techStack.testing?.credentials?.usernameEnvVar || 'TEST_USER_USERNAME'}\`
- **Password Variable**: \`${techStack.testing?.credentials?.passwordEnvVar || 'TEST_USER_PASSWORD'}\`

## Login Selectors

| Element | Selector |
|---------|----------|
| Username | \`${selectors.username || '[data-testid="username-input"]'}\` |
| Password | \`${selectors.password || '[data-testid="password-input"]'}\` |
| Login Button | \`${selectors.loginButton || '[data-testid="login-submit"]'}\` |
| Success Indicator | \`${selectors.loginSuccess || '[data-testid="dashboard"]'}\` |

## E2E Testing

- **Framework**: ${techStack.testing?.e2e?.framework || 'playwright'}
- **Config**: ${techStack.testing?.e2e?.configFile || 'playwright.config.ts'}
- **Command**: \`${techStack.testing?.e2e?.testCommand || 'npx playwright test'}\`

## Unit Testing

- **Framework**: ${techStack.testing?.unit?.framework || 'vitest'}
- **Command**: \`${techStack.testing?.unit?.testCommand || 'npm test'}\`

## Deployment

- **Frontend Platform**: ${techStack.deployment?.frontend?.platform || 'not configured'}
- **Backend Platform**: ${techStack.deployment?.backend?.platform || 'not configured'}

## Task Workflow

1. Debug with curl/fetch first
2. ${techStack.testing?.e2e?.framework ? `Run ${techStack.testing.e2e.framework} tests` : 'Manual testing'}
3. Commit after each task

---
*Generated by gtask-init on ${new Date().toISOString()}*
`;
}
