/**
 * GitHub Configuration Templates
 *
 * Template generation for GitHub config tools.
 */

/**
 * Generate the GitHub settings updater script
 */
export function generateGitHubSettingsUpdater() {
  return `/**
 * GitHub Settings Updater
 *
 * Reads settings from .claude/settings.json and updates
 * GitHub-related commands and configurations.
 *
 * Usage: node .claude/hooks/tools/github-settings-updater.js
 *
 * Generated by: gtask claude-settings
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..', '..', '..');

/**
 * Load settings from .claude/settings.json
 */
function loadSettings() {
  const settingsPath = join(projectRoot, '.claude', 'settings.json');

  if (!existsSync(settingsPath)) {
    console.error('ERROR: .claude/settings.json not found');
    console.log('Run "gtask claude-settings" to create it.');
    process.exit(1);
  }

  try {
    return JSON.parse(readFileSync(settingsPath, 'utf8'));
  } catch (err) {
    console.error('ERROR: Failed to parse settings.json:', err.message);
    process.exit(1);
  }
}

/**
 * Update GitHub commands with settings
 */
function updateCommands(settings) {
  const github = settings.github;
  if (!github) {
    console.log('No GitHub settings found.');
    return;
  }

  const commandsDir = join(projectRoot, '.claude', 'commands');
  if (!existsSync(commandsDir)) {
    console.log('No .claude/commands directory found.');
    return;
  }

  // List of GitHub-related commands to check
  const githubCommands = [
    'github-create-task.md',
    'github-task-start.md',
    'github-update.md',
    'github-validate.md',
    'create-task-list.md',
  ];

  let updatedCount = 0;

  for (const cmdFile of githubCommands) {
    const cmdPath = join(commandsDir, cmdFile);
    if (!existsSync(cmdPath)) continue;

    let content = readFileSync(cmdPath, 'utf8');
    let modified = false;

    // Update repository references
    if (github.repository?.owner && github.repository?.name) {
      const repoPattern = /--repo [a-zA-Z0-9_-]+\\/[a-zA-Z0-9_-]+/g;
      const newRepo = \`--repo \${github.repository.owner}/\${github.repository.name}\`;
      if (content.match(repoPattern)) {
        content = content.replace(repoPattern, newRepo);
        modified = true;
      }
    }

    // Update project number references
    if (github.project?.number) {
      const projectPattern = /project-number:\\s*\\d+/g;
      const newProject = \`project-number: \${github.project.number}\`;
      if (content.match(projectPattern)) {
        content = content.replace(projectPattern, newProject);
        modified = true;
      }
    }

    if (modified) {
      writeFileSync(cmdPath, content, 'utf8');
      console.log(\`Updated: \${cmdFile}\`);
      updatedCount++;
    }
  }

  console.log(\`\\nUpdated \${updatedCount} command files.\`);
}

/**
 * Update CLAUDE.md with settings
 */
function updateClaudeMd(settings) {
  const github = settings.github;
  if (!github) return;

  const claudeMdPath = join(projectRoot, 'CLAUDE.md');
  if (!existsSync(claudeMdPath)) {
    console.log('No CLAUDE.md found.');
    return;
  }

  // For now, just log that CLAUDE.md could be updated
  // More sophisticated updates could be added here
  console.log('CLAUDE.md exists - manual updates may be needed for complex changes.');
}

/**
 * Main execution
 */
function main() {
  console.log('GitHub Settings Updater');
  console.log('=======================\\n');

  const settings = loadSettings();

  console.log('Loaded settings:');
  if (settings.github?.repository) {
    console.log(\`  Repository: \${settings.github.repository.owner}/\${settings.github.repository.name}\`);
  }
  if (settings.github?.project?.number) {
    console.log(\`  Project: #\${settings.github.project.number}\`);
  }
  console.log('');

  updateCommands(settings);
  updateClaudeMd(settings);

  console.log('\\nDone!');
}

main();
`;
}
