/**
 * Menu Command Generator
 *
 * Generates the interactive ASCII menu slash command with quick keys
 * and categorized command tables.
 */

import { getVersion } from '../../../utils.js';
import { AVAILABLE_COMMANDS } from '../features.js';

/**
 * Generate menu command content
 * Creates the interactive ASCII menu slash command
 */
export function generateMenuCommand(projectName, installedCommands, installedAgents, installedSkills, installedHooks) {
  const date = new Date().toISOString().split('T')[0];

  // Build command table from installed commands
  const commandTable = installedCommands
    .map((name) => {
      const cmd = AVAILABLE_COMMANDS.find((c) => c.name === name);
      return cmd ? `| \`/${name}\` | ${cmd.category} | ${cmd.description} |` : null;
    })
    .filter(Boolean)
    .join('\n');

  // Build agent list
  const agentList =
    installedAgents.length > 0
      ? installedAgents.map((a) => `- **${a}** - Custom agent`).join('\n')
      : '- No agents installed yet';

  // Build skill list
  const skillList =
    installedSkills.length > 0
      ? installedSkills.map((s) => `- **/${s}** - Custom skill`).join('\n')
      : '- No skills installed yet';

  // Build hook list
  const hookList =
    installedHooks.length > 0
      ? installedHooks.map((h) => `- **${h}** - Active hook`).join('\n')
      : '- No hooks installed yet';

  return `---
description: Interactive project menu - Quick access to all commands, agents, skills, and tools
---

# ${projectName} - Interactive Menu

**DISPLAY INSTRUCTION:** You MUST display this ENTIRE menu verbatim in a code block. Do NOT summarize. Do NOT paraphrase. Show the FULL ASCII menu below.

\`\`\`
╔═══════════════════════════════════════════════════════════════╗
║  ${projectName.substring(0, 50).padEnd(50)}             ║
╠═══════════════════════════════════════════════════════════════╣
║                                                               ║
║  QUICK KEYS (type single character):                          ║
║  ─────────────────────────────────────────────────────────    ║
║  [1] TOP TASK    - Start #1 from Project Board                ║
║  [2] NEXT TASK   - Pick next task                             ║
║  [3] COMMIT      - git status + staged commit                 ║
║  [4] BOARD       - /github-project-menu                       ║
║  [5] ROADMAP     - /create-roadmap or /roadmap-status         ║
║  [M] DEPLOY      - /deploy-full (frontend + backend)          ║
║  [O] E2E TESTS   - /e2e-test                                  ║
║  [T] TASK LIST   - /create-task-list                          ║
║  [A] AUDIT       - /claude-audit                              ║
║  [X] SETTINGS    - Configuration options                      ║
║                                                               ║
║  COMMANDS BY CATEGORY:                                        ║
║  ─────────────────────────────────────────────────────────    ║
║  Planning:    /phase-dev-plan  /create-roadmap  /roadmap-status║
║  GitHub:      /github-task-start  /github-project-menu        ║
║  Testing:     /e2e-test  /ralph  /create-smoke-test           ║
║  Refactor:    /refactor-workflow  /refactor-analyze           ║
║  Deploy:      /deploy-full                                    ║
║  Marketing:   /landing-page-generator  /landing-page-toggle   ║
║  Claude:      /create-agent  /create-hook  /create-skill      ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
\`\`\`

Type a key (1-5, M, O, T, A, X) or a command name, or describe what you need.

---

## Quick Access Keys

Reply with a **single character** for quick navigation:

| Key | Action | Description |
|-----|--------|-------------|
| **1** | TOP TASK | Start #1 from Project Board |
| **2** | NEXT TASK | Pick next task |
| **3** | Commit | git status + staged commit |
| **4** | GitHub Board | /github-project-menu |
| **5** | Roadmap | /create-roadmap or /roadmap-status |
| **M** | Deploy | /deploy-full |
| **O** | E2E Tests | /e2e-test |
| **T** | Task List | /create-task-list |
| **A** | Claude Audit | /claude-audit |
| **X** | Settings | /claude-settings |

## All Commands

| Command | Category | Description |
|---------|----------|-------------|
${commandTable}

## Agents

${agentList}

## Skills

${skillList}

## Active Hooks

${hookList}

---

*Generated by Claude CLI Advanced Starter Pack v${getVersion()} on ${date}*
`;
}
