/**
 * Phase Synchronization
 *
 * Create and update GitHub issues for roadmap phases and epics.
 */

import ora from 'ora';
import { safeCreateIssue, safeAddIssueComment, safeCloseIssue } from '../../utils/safe-exec.js';
import { getRepoInfo } from './cli.js';

/**
 * Create a GitHub issue for a roadmap phase
 *
 * @param {Object} phase - Phase object
 * @param {Object} roadmap - Parent roadmap
 * @param {Object} options - Creation options
 * @returns {Object} Created issue info
 */
export async function createPhaseIssue(phase, roadmap, options = {}) {
  const repoInfo = getRepoInfo();
  const owner = options.owner || repoInfo?.owner;
  const repo = options.repo || repoInfo?.repo;

  if (!owner || !repo) {
    throw new Error('Could not determine repository');
  }

  const title = `[Phase] ${phase.phase_title}`;
  const body = generatePhaseIssueBody(phase, roadmap);
  const labels = ['phase-dev', `roadmap:${roadmap.slug}`];

  if (phase.complexity) {
    labels.push(`complexity:${phase.complexity.toLowerCase()}`);
  }

  // Use safe execution to prevent shell injection
  return safeCreateIssue({
    owner,
    repo,
    title,
    body,
    labels,
  });
}

/**
 * Generate issue body for a roadmap phase
 */
export function generatePhaseIssueBody(phase, roadmap) {
  let body = `## ${phase.phase_title}\n\n`;
  body += `**Roadmap:** ${roadmap.title}\n`;
  body += `**Phase ID:** \`${phase.phase_id}\`\n`;
  body += `**Complexity:** ${phase.complexity || 'M'}\n`;
  body += `**Status:** ${phase.status || 'pending'}\n\n`;

  if (phase.goal) {
    body += `### Goal\n\n${phase.goal}\n\n`;
  }

  if (phase.inputs?.issues?.length > 0) {
    body += `### Related Issues\n\n`;
    for (const issue of phase.inputs.issues) {
      body += `- ${issue}\n`;
    }
    body += '\n';
  }

  if (phase.outputs?.length > 0) {
    body += `### Deliverables\n\n`;
    for (const output of phase.outputs) {
      body += `- [ ] ${output}\n`;
    }
    body += '\n';
  }

  if (phase.dependencies?.length > 0) {
    body += `### Dependencies\n\n`;
    body += `This phase depends on: ${phase.dependencies.join(', ')}\n\n`;
  }

  body += `---\n`;
  body += `*Part of [${roadmap.title}] roadmap*\n`;
  body += `*Generated by CCASP*`;

  return body;
}

/**
 * Create an epic issue for a roadmap
 *
 * @param {Object} roadmap - Roadmap object
 * @param {Object} options - Creation options
 * @returns {Object} Created issue info
 */
export async function createRoadmapEpic(roadmap, options = {}) {
  const repoInfo = getRepoInfo();
  const owner = options.owner || repoInfo?.owner;
  const repo = options.repo || repoInfo?.repo;

  if (!owner || !repo) {
    throw new Error('Could not determine repository');
  }

  const title = `[Roadmap] ${roadmap.title}`;
  const body = generateRoadmapEpicBody(roadmap);
  const labels = ['roadmap', 'epic'];

  // Use safe execution to prevent shell injection
  return safeCreateIssue({
    owner,
    repo,
    title,
    body,
    labels,
  });
}

/**
 * Generate issue body for roadmap epic
 */
export function generateRoadmapEpicBody(roadmap) {
  const phases = roadmap.phases || [];

  let body = `## ${roadmap.title}\n\n`;

  if (roadmap.description) {
    body += `${roadmap.description}\n\n`;
  }

  body += `### Progress\n\n`;
  body += `**Phases:** ${phases.filter(p => p.status === 'completed').length}/${phases.length} complete\n`;
  body += `**Status:** ${roadmap.status || 'planning'}\n\n`;

  // Dependency graph
  if (phases.length > 1) {
    body += `### Dependency Graph\n\n`;
    body += '```mermaid\n';
    body += 'graph LR\n';

    for (let i = 0; i < phases.length; i++) {
      const phase = phases[i];
      const nodeId = phase.phase_id.replace(/-/g, '_');
      body += `  ${nodeId}["${phase.phase_title}"]\n`;
    }

    for (const phase of phases) {
      if (phase.dependencies?.length > 0) {
        const nodeId = phase.phase_id.replace(/-/g, '_');
        for (const dep of phase.dependencies) {
          const depId = dep.replace(/-/g, '_');
          body += `  ${depId} --> ${nodeId}\n`;
        }
      }
    }

    body += '```\n\n';
  }

  // Phase list
  body += `### Phases\n\n`;

  for (const phase of phases) {
    const statusIcon = phase.status === 'completed' ? '✅' :
                       phase.status === 'in_progress' ? '🔄' :
                       phase.status === 'blocked' ? '🚫' : '⬜';
    body += `${statusIcon} **${phase.phase_title}** (${phase.complexity || 'M'})\n`;
    if (phase.goal) {
      body += `   ${phase.goal.substring(0, 100)}${phase.goal.length > 100 ? '...' : ''}\n`;
    }
    body += '\n';
  }

  body += `---\n`;
  body += `*Generated by CCASP Roadmap Orchestration Framework*`;

  return body;
}

/**
 * Add a progress comment to an issue
 *
 * @param {number} issueNumber - Issue number
 * @param {string} comment - Comment text
 * @param {Object} options - Options with owner/repo
 * @returns {boolean} Success status
 */
export function addProgressComment(issueNumber, comment, options = {}) {
  const repoInfo = getRepoInfo();
  const owner = options.owner || repoInfo?.owner;
  const repo = options.repo || repoInfo?.repo;

  if (!owner || !repo) return false;

  return safeAddIssueComment({
    owner,
    repo,
    issueNumber,
    body: comment,
  });
}

/**
 * Close an issue
 *
 * @param {number} issueNumber - Issue number
 * @param {string} reason - Closing reason
 * @param {Object} options - Options with owner/repo
 * @returns {boolean} Success status
 */
export function closeIssue(issueNumber, reason, options = {}) {
  const repoInfo = getRepoInfo();
  const owner = options.owner || repoInfo?.owner;
  const repo = options.repo || repoInfo?.repo;

  if (!owner || !repo) return false;

  return safeCloseIssue({
    owner,
    repo,
    issueNumber,
    comment: reason ? `✅ ${reason}` : undefined,
  });
}

/**
 * Sync roadmap progress to GitHub
 *
 * @param {Object} roadmap - Roadmap object
 * @param {Object} options - Sync options
 * @returns {Object} Sync result
 */
export async function syncToGitHub(roadmap, options = {}) {
  const spinner = ora('Syncing roadmap to GitHub...').start();
  const results = { synced: 0, failed: 0, errors: [] };

  for (const phase of roadmap.phases || []) {
    const issueNumber = phase.github_issue_number;
    if (!issueNumber) continue;

    try {
      const progress = phase.metadata?.completed_tasks || 0;
      const total = phase.metadata?.total_tasks || 0;
      const percentage = total > 0 ? Math.round((progress / total) * 100) : 0;

      const comment = `📊 **Progress Update**\n\nStatus: ${phase.status}\nTasks: ${progress}/${total} (${percentage}%)\n\n_Updated by CCASP_`;

      const success = addProgressComment(issueNumber, comment, options);

      if (success) {
        results.synced++;

        // Close if completed
        if (phase.status === 'completed') {
          closeIssue(issueNumber, 'Phase completed', options);
        }
      } else {
        results.failed++;
      }
    } catch (e) {
      results.failed++;
      results.errors.push(`Phase ${phase.phase_id}: ${e.message}`);
    }
  }

  spinner.succeed(`Synced ${results.synced} phases${results.failed > 0 ? `, ${results.failed} failed` : ''}`);

  return results;
}
