/**
 * Documentation Generator - GitHub Issue Integration
 *
 * Creates GitHub issues with full phase/task breakdown for phase-dev plans.
 */

import { checkGhCli, getRepoInfo } from '../../../roadmap/github-integration.js';
import { execSync } from 'child_process';

/**
 * Create GitHub issue for phase-dev plan
 * @param {Object} config - Project configuration
 * @param {Object} explorationData - L2 exploration data (optional)
 * @returns {Object} Created issue info
 */
export async function createPhaseDevGitHubIssue(config, explorationData = null) {
  const ghCheck = checkGhCli();
  if (!ghCheck.available || !ghCheck.authenticated) {
    return { success: false, error: ghCheck.error || 'gh CLI not available' };
  }

  const repoInfo = getRepoInfo();
  if (!repoInfo) {
    return { success: false, error: 'Could not determine repository' };
  }

  const { projectName, projectSlug } = config;

  const body = generatePhaseDevIssueBody(config, explorationData);

  try {
    const result = execSync(
      `gh issue create --title "${escapeShell(`\u{1f4cb} Phase Dev: ${projectName}`)}" --body "${escapeShell(body)}"`,
      { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }
    );

    const urlMatch = result.match(/https:\/\/github\.com\/[^\s]+/);
    const issueUrl = urlMatch ? urlMatch[0] : null;
    const numberMatch = issueUrl?.match(/\/issues\/(\d+)/);
    const issueNumber = numberMatch ? parseInt(numberMatch[1]) : null;

    return {
      success: true,
      url: issueUrl,
      number: issueNumber,
    };
  } catch (error) {
    return {
      success: false,
      error: error.message,
    };
  }
}

/**
 * Generate GitHub issue body with full phase/task breakdown
 */
function generatePhaseDevIssueBody(config, explorationData) {
  const { projectName, projectSlug, description, phases, architecture, scale } = config;
  const totalTasks = phases.reduce((sum, p) => sum + (p.tasks?.length || 0), 0);

  let body = `## ${projectName}

**Slug:** \`${projectSlug}\`
**Scale:** ${scale || 'M'}
**Phases:** ${phases.length}
**Total Tasks:** ${totalTasks}
**Exploration Docs:** \`.claude/exploration/${projectSlug}/\`

### Description
${description || 'No description provided.'}

---

## Architecture
${architecture?.summary || 'Not specified'}

`;

  if (explorationData) {
    body += `## Codebase Analysis

### Key Statistics
- Files analyzed: ${explorationData.summary?.filesAnalyzed || 0}
- Code snippets extracted: ${explorationData.summary?.snippetsExtracted || 0}
- Confidence: ${explorationData.summary?.confidence || 'medium'}

### Recommended Primary Agent
**${explorationData.delegation?.primaryAgent || 'general-implementation-agent'}** - ${explorationData.delegation?.primaryAgentReason || 'Best fit for project'}

`;
  }

  body += `---

## Phase Breakdown

`;

  phases.forEach((phase, phaseIdx) => {
    const phaseNum = phaseIdx + 1;
    const tasks = phase.tasks || [];

    body += `### Phase ${phaseNum}: ${phase.name}
**Objective:** ${phase.objective || phase.description || 'Not specified'}
**Complexity:** ${phase.complexity || 'M'}
**Agent:** ${phase.assignedAgent || 'TBD'}
**Dependencies:** ${formatDependencies(phase.dependencies)}

#### Tasks
`;

    tasks.forEach((task, taskIdx) => {
      const taskId = task.id || `${phaseNum}.${taskIdx + 1}`;
      const criteria = task.acceptanceCriteria || task.acceptance_criteria || [];

      body += `- [ ] **${taskId}** ${task.title}
`;

      if (task.files && task.files.length > 0) {
        body += `  - Files: ${task.files.map(f => `\`${f.path || f}\``).slice(0, 3).join(', ')}
`;
      }
      if (task.assignedAgent) {
        body += `  - Agent: ${task.assignedAgent}
`;
      }
      if (criteria.length > 0) {
        body += `  - Criteria: ${criteria.slice(0, 2).join(', ')}
`;
      }
    });

    body += `
#### Phase ${phaseNum} Validation
`;
    const validationCriteria = phase.validationCriteria || ['All tasks complete', 'No blocking issues'];
    validationCriteria.forEach(c => {
      body += `- [ ] ${c}
`;
    });

    body += `
---

`;
  });

  body += `## Execution Checklist
- [ ] Review exploration docs in \`.claude/exploration/${projectSlug}/\`
- [ ] Start Phase 1
${phases.map((p, i) => `- [ ] Complete Phase ${i + 1} validation`).join('\n')}
- [ ] Final testing
- [ ] Close this issue with summary

---
*Exploration docs: \`.claude/exploration/${projectSlug}/\`*
*Generated by CCASP Phase-Dev Planning*
`;

  return body;
}

/**
 * Format dependencies for display
 */
function formatDependencies(deps) {
  if (!deps || deps.length === 0) return 'None';
  return deps.join(', ');
}

/**
 * Escape shell characters
 */
function escapeShell(str) {
  return str.replace(/"/g, '\\"').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}
