/**
 * Core Feature Definitions
 *
 * Defines core and non-deployment/non-GitHub optional features.
 */

export const CORE_FEATURES = [
  {
    name: 'tokenManagement',
    label: 'Token Budget Management',
    description: 'Monitor and manage Claude API token usage with automatic compaction warnings, archive suggestions, and respawn thresholds. Includes hooks that track usage per session.',
    commands: ['context-audit'],
    hooks: ['context-guardian', 'token-budget-loader', 'tool-output-cacher'],
    default: false,
    requiresPostConfig: false,
  },
  {
    name: 'happyMode',
    label: 'Happy Engineering Integration',
    description: 'Integration with Happy Coder mobile app for remote session control, checkpoint management, and mobile-optimized responses.',
    commands: ['happy-start'],
    hooks: ['happy-checkpoint-manager', 'happy-title-generator', 'happy-mode-detector', 'context-injector'],
    binaries: ['happy-start.ps1'],
    default: false,
    requiresPostConfig: true,
    npmPackage: 'happy-coder',
    npmInstallPrompt: 'Install Happy Coder CLI globally? (npm i -g happy-coder)',
  },
  {
    name: 'phasedDevelopment',
    label: 'Phased Development System',
    description: 'Generate production-ready development plans with 95%+ success criteria, automatic scaling (S/M/L), and progress tracking. Creates PROGRESS.json files for state persistence.',
    commands: ['phase-dev-plan', 'phase-track'],
    hooks: ['phase-dev-enforcer'],
    default: true,
    requiresPostConfig: false,
  },
  {
    name: 'tunnelServices',
    label: 'Tunnel Service Integration',
    description: 'Expose local development server for mobile testing or webhooks. Supports ngrok, localtunnel, cloudflare-tunnel, and serveo. No default service - configured after installation via /menu.',
    commands: ['tunnel-start', 'tunnel-stop'],
    hooks: [],
    default: false,
    requiresPostConfig: true,
  },
  {
    name: 'advancedHooks',
    label: 'Advanced Hook Suite',
    description: 'Extended hook system with session management, git commit tracking, branch validation, issue detection, token monitoring, autonomous logging, and phase validation gates.',
    commands: [],
    hooks: [
      'session-id-generator',
      'git-commit-tracker',
      'branch-merge-checker',
      'issue-completion-detector',
      'token-usage-monitor',
      'autonomous-decision-logger',
      'phase-validation-gates',
    ],
    default: false,
    requiresPostConfig: false,
  },
  {
    name: 'skillTemplates',
    label: 'Skill Creator Templates',
    description: 'Pre-built skills for agent creation, hook creation, and RAG-enhanced agent building. Provides best-practice templates for extending Claude Code.',
    commands: [],
    hooks: [],
    skills: ['agent-creator', 'hook-creator', 'rag-agent-creator', 'panel'],
    default: true,
    requiresPostConfig: false,
  },
  {
    name: 'refactoring',
    label: 'Refactoring Tools',
    description: 'Code quality commands for linting, cleanup, and safe refactoring. Includes pre-commit checks, auto-fix, and safety checklists.',
    commands: ['refactor-check', 'refactor-cleanup', 'refactor-prep'],
    hooks: [],
    default: false,
    requiresPostConfig: false,
  },
  {
    name: 'testing',
    label: 'Advanced Testing',
    description: 'Extended testing capabilities including smoke test generation and test coverage analysis.',
    commands: ['create-smoke-test'],
    hooks: [],
    default: false,
    requiresPostConfig: false,
  },
  {
    name: 'ralphLoop',
    label: 'Ralph Loop Testing',
    description: 'Continuous test-fix cycle automation. Runs tests, detects failures, applies fixes, and repeats until all tests pass or max iterations reached.',
    commands: ['ralph'],
    hooks: ['ralph-loop-enforcer'],
    default: true,
    requiresPostConfig: false,
  },
  {
    name: 'refactorAudit',
    label: 'Refactor Audit System',
    description: 'Monitors task/phase completions and flags files over 500 lines for refactoring. Offers guided workflow: new branch, task list, GitHub issue, specialist agent deployment.',
    commands: ['refactor-workflow', 'refactor-analyze', 'golden-master'],
    hooks: ['refactor-audit', 'refactor-verify', 'refactor-transaction'],
    skills: ['refactor-react', 'refactor-fastapi'],
    default: true,
    requiresPostConfig: false,
  },
  {
    name: 'autoStackAgents',
    label: 'Auto Stack-Specific Agents',
    description: 'Automatically generate specialist agents based on your tech stack (React, FastAPI, Prisma, etc.). Includes delegation hooks for intelligent task routing.',
    commands: ['generate-agents'],
    hooks: ['task-classifier', 'agent-delegator', 'delegation-enforcer'],
    default: true,
    requiresPostConfig: false,
  },
  {
    name: 'projectExplorer',
    label: 'Project Explorer (Fresh Scaffolding)',
    description: 'Interactive wizard for scaffolding new projects in empty directories. Interviews user about project goals, creates skeleton files, installs dependencies, and hands off to implementation.',
    commands: ['project-explorer'],
    hooks: [],
    default: true,
    requiresPostConfig: false,
  },
  {
    name: 'roadmapSystem',
    label: 'Roadmap Management System',
    description: 'Multi-phase roadmap creation with automatic GitHub issue hierarchy (epic → child issues), complexity detection that recommends roadmaps for large plans, state tracking between PROGRESS.json and ROADMAP.json, automatic phase advancement, and auto-generated documentation.',
    commands: ['create-roadmap', 'roadmap-status'],
    hooks: ['complexity-analyzer', 'roadmap-state-tracker', 'documentation-generator'],
    default: true,
    requiresPostConfig: false,
  },
  {
    name: 'agentOrchestration',
    label: 'Agent Orchestration System',
    description: 'Hierarchical agent orchestration (L1/L2/L3) for phased development. L1 orchestrator spawns L2 specialists by domain, L2s spawn L3 workers for atomic tasks. Auto-updates PROGRESS.json, syncs to GitHub issues, enforces delegation hierarchy.',
    commands: ['orchestration-guide'],
    hooks: [
      'orchestrator-init',
      'orchestrator-enforcer',
      'hierarchy-validator',
      'progress-tracker',
      'github-progress-sync',
      'l2-completion-reporter',
      'l3-parallel-executor',
      'subagent-context-injector',
      'completion-verifier',
      'agent-error-recovery',
      'orchestrator-audit-logger',
    ],
    default: true,
    requiresPostConfig: false,
  },
  {
    name: 'aiConstitution',
    label: 'AI Constitution Framework',
    description: 'Code style and architecture preferences enforcement system with YAML schema, hook-based validation (1-in-20 sampling), and configurable presets (senior, minimal, strict, custom). Ensures Claude follows project coding standards.',
    commands: ['ai-constitution-framework'],
    hooks: ['constitution-enforcer'],
    default: false,
    requiresPostConfig: true,
    postConfigSteps: [
      'Run ccasp constitution-init to create constitution.yaml',
      'Customize rules in .claude/config/constitution.yaml',
      'Optionally adjust sampling rate for performance vs coverage',
    ],
  },
];
