/**
 * Reference documentation generation for exploration docs
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { createExplorationDir } from './directory.js';

/**
 * Save reference files markdown
 * @param {string} slug - Project slug
 * @param {Object} files - Files object with modify, reference, tests arrays
 * @param {string} cwd - Current working directory
 */
export function saveReferenceFiles(slug, files, cwd = process.cwd()) {
  const dir = createExplorationDir(slug, cwd);

  const modifyFiles = files.modify || [];
  const referenceFiles = files.reference || [];
  const testFiles = files.tests || [];

  let content = `# Reference Files: ${slug}

## Files to MODIFY (Primary)
| File | Reason | Complexity |
|------|--------|------------|
`;

  if (modifyFiles.length === 0) {
    content += '| *No files identified* | - | - |\n';
  } else {
    modifyFiles.forEach(f => {
      content += `| \`${f.path}\` | ${f.reason || '-'} | ${f.complexity || 'M'} |\n`;
    });
  }

  content += `

## Files to REFERENCE (Dependencies)
| File | Reason |
|------|--------|
`;

  if (referenceFiles.length === 0) {
    content += '| *No dependencies identified* | - |\n';
  } else {
    referenceFiles.forEach(f => {
      content += `| \`${f.path}\` | ${f.reason || '-'} |\n`;
    });
  }

  content += `

## Test Files to UPDATE
| File | Coverage Area |
|------|---------------|
`;

  if (testFiles.length === 0) {
    content += '| *No test files identified* | - |\n';
  } else {
    testFiles.forEach(f => {
      content += `| \`${f.path}\` | ${f.coverage || '-'} |\n`;
    });
  }

  content += `

---
*Generated by CCASP L2 Exploration*
`;

  writeFileSync(join(dir, 'REFERENCE_FILES.md'), content, 'utf8');
  return join(dir, 'REFERENCE_FILES.md');
}

/**
 * Save agent delegation markdown
 * @param {string} slug - Project slug
 * @param {Object} delegation - Delegation configuration
 * @param {string} cwd - Current working directory
 */
export function saveAgentDelegation(slug, delegation, cwd = process.cwd()) {
  const dir = createExplorationDir(slug, cwd);

  const primaryAgent = delegation.primaryAgent || 'general-implementation-agent';
  const taskAssignments = delegation.taskAssignments || [];
  const executionSequence = delegation.executionSequence || [];

  let content = `# Agent Delegation: ${slug}

## Recommended Primary Agent
**${primaryAgent}** - ${delegation.primaryAgentReason || 'Best fit for overall project domain'}

## Task-Agent Assignments
| Phase | Task | Recommended Agent | Reason |
|-------|------|-------------------|--------|
`;

  if (taskAssignments.length === 0) {
    content += '| - | - | *No assignments* | - |\n';
  } else {
    taskAssignments.forEach(a => {
      content += `| ${a.phase || '-'} | ${a.task || '-'} | ${a.agent || '-'} | ${a.reason || '-'} |\n`;
    });
  }

  content += `

## Execution Sequence
`;

  if (executionSequence.length === 0) {
    content += '*No specific sequence defined - follow phase order.*\n';
  } else {
    executionSequence.forEach((seq, idx) => {
      content += `${idx + 1}. **${seq.agent}** - ${seq.scope || 'General'}\n`;
    });
  }

  content += `

## Agent Capabilities Reference
| Agent | Domains | Tools |
|-------|---------|-------|
| frontend-specialist | UI, Components, Styling | Read, Write, Edit, Glob, Grep |
| backend-specialist | API, Database, Auth | Read, Write, Edit, Bash, Glob |
| testing-specialist | Unit, E2E, Coverage | Read, Write, Bash, Glob |
| deployment-specialist | CI/CD, Docker, Cloud | Read, Bash, Glob |
| general-implementation | Full-stack | All tools |

---
*Generated by CCASP L2 Exploration*
`;

  writeFileSync(join(dir, 'AGENT_DELEGATION.md'), content, 'utf8');
  return join(dir, 'AGENT_DELEGATION.md');
}
