/**
 * Summary generation functions for exploration documentation
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { createExplorationDir } from './directory.js';

/**
 * Format domain distribution for markdown
 */
function formatDomainDistribution(domains) {
  if (!domains || Object.keys(domains).length === 0) return '- No domains detected';

  return Object.entries(domains)
    .map(([domain, count]) => `- **${domain}:** ${count} items`)
    .join('\n');
}

/**
 * Save exploration summary markdown
 * @param {string} slug - Project slug
 * @param {Object} summary - Summary data
 * @param {string} cwd - Current working directory
 */
export function saveExplorationSummary(slug, summary, cwd = process.cwd()) {
  const dir = createExplorationDir(slug, cwd);
  const timestamp = new Date().toISOString();

  const content = `# Exploration Summary: ${summary.title || slug}

**Generated:** ${timestamp}
**Status:** ${summary.status || 'complete'}
**Confidence:** ${summary.confidence || 'medium'}

## Overview
${summary.overview || 'No overview provided.'}

## Key Statistics
- Files analyzed: ${summary.filesAnalyzed || 0}
- Code snippets extracted: ${summary.snippetsExtracted || 0}
- Phases identified: ${summary.phasesIdentified || 0}
- Tasks generated: ${summary.tasksGenerated || 0}
- Recommended agents: ${(summary.recommendedAgents || []).join(', ') || 'None'}

## Quick Reference
- [Code Snippets](./CODE_SNIPPETS.md)
- [Reference Files](./REFERENCE_FILES.md)
- [Agent Delegation](./AGENT_DELEGATION.md)
- [Phase Breakdown](./PHASE_BREAKDOWN.md)

## Domain Distribution
${summary.domains ? formatDomainDistribution(summary.domains) : '- Not analyzed'}

## Complexity Assessment
${summary.complexityAssessment || '- Not assessed'}

---
*Generated by CCASP L2 Exploration*
`;

  writeFileSync(join(dir, 'EXPLORATION_SUMMARY.md'), content, 'utf8');
  return join(dir, 'EXPLORATION_SUMMARY.md');
}

/**
 * Save code snippets markdown
 * @param {string} slug - Project slug
 * @param {Array} snippets - Array of snippet objects
 * @param {string} cwd - Current working directory
 */
export function saveCodeSnippets(slug, snippets, cwd = process.cwd()) {
  const dir = createExplorationDir(slug, cwd);

  let content = `# Code Snippets: ${slug}

`;

  if (!snippets || snippets.length === 0) {
    content += '*No code snippets extracted.*\n';
  } else {
    snippets.forEach((snippet, idx) => {
      content += `## Snippet ${idx + 1}: ${snippet.description || 'Untitled'}
**File:** \`${snippet.file || 'unknown'}\`
**Lines:** ${snippet.startLine || '?'}-${snippet.endLine || '?'}
**Relevance:** ${snippet.relevance || 'General reference'}

\`\`\`${snippet.language || ''}
${snippet.content || '// No content'}
\`\`\`

---
`;
    });
  }

  writeFileSync(join(dir, 'CODE_SNIPPETS.md'), content, 'utf8');
  return join(dir, 'CODE_SNIPPETS.md');
}

/**
 * Save machine-readable findings JSON
 * @param {string} slug - Project slug
 * @param {Object} findings - Complete findings object
 * @param {string} cwd - Current working directory
 */
export function saveFindingsJson(slug, findings, cwd = process.cwd()) {
  const dir = createExplorationDir(slug, cwd);

  const enrichedFindings = {
    ...findings,
    metadata: {
      ...(findings.metadata || {}),
      slug,
      generatedAt: new Date().toISOString(),
      version: '1.0',
      generator: 'ccasp-l2-exploration',
    },
  };

  writeFileSync(
    join(dir, 'findings.json'),
    JSON.stringify(enrichedFindings, null, 2),
    'utf8'
  );

  return join(dir, 'findings.json');
}
