/**
 * Agent launcher script generators
 */

/**
 * Generate Windows batch launcher
 */
export function generateWindowsBatch() {
  return `@echo off
REM ============================================================
REM Claude Agent-Only Mode Launcher (Windows Batch)
REM ============================================================
REM
REM This batch file launches the PowerShell script that starts
REM Claude in Agent-Only execution mode with policy enforcement
REM via --append-system-prompt.
REM
REM Usage:
REM   - Double-click this file to start Claude in Agent-Only mode
REM   - Or run from command line: start-agent-only.bat
REM   - With arguments: start-agent-only.bat --permission-mode acceptEdits
REM
REM Generated by: gtask claude-settings
REM ============================================================

setlocal

REM Get the directory where this batch file is located
set "SCRIPT_DIR=%~dp0"
set "PS_SCRIPT=%SCRIPT_DIR%claude-agent-only.ps1"

REM Check if PowerShell script exists
if not exist "%PS_SCRIPT%" (
    echo ERROR: PowerShell script not found!
    echo Expected: %PS_SCRIPT%
    echo.
    echo Please ensure claude-agent-only.ps1 exists in the same directory.
    pause
    exit /b 1
)

REM Execute PowerShell script with execution policy bypass
echo Starting Claude in Agent-Only mode...
echo.

powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%PS_SCRIPT%" %*

REM Capture exit code from PowerShell
set EXIT_CODE=%ERRORLEVEL%

REM Exit with the same code
exit /b %EXIT_CODE%
`;
}

/**
 * Generate PowerShell launcher
 */
export function generatePowerShellLauncher() {
  return `<#
.SYNOPSIS
    Launches Claude in Agent-Only Execution Mode

.DESCRIPTION
    This script loads the agent definitions and policy file, then launches
    Claude with the agent-only execution policy appended to the system prompt.

.PARAMETER Args
    Additional arguments to pass to the claude CLI

.EXAMPLE
    .\\claude-agent-only.ps1
    .\\claude-agent-only.ps1 --permission-mode acceptEdits

Generated by: gtask claude-settings
#>

param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$RemainingArgs
)

$ErrorActionPreference = "Stop"

# Define paths
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ClaudeDir = Join-Path $ScriptDir ".claude"
$PolicyFile = Join-Path $ClaudeDir "AGENT_ONLY_POLICY.md"
$AgentsFile = Join-Path $ClaudeDir "agents.json"

# Banner
Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "   CLAUDE - AGENT-ONLY EXECUTION MODE (STRICT)" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# Validate required files exist
if (-not (Test-Path $PolicyFile)) {
    Write-Host "ERROR: Policy file not found!" -ForegroundColor Red
    Write-Host "Expected: $PolicyFile" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Run 'gtask claude-settings' to create it." -ForegroundColor Yellow
    exit 1
}

if (-not (Test-Path $AgentsFile)) {
    Write-Host "WARNING: Agents file not found." -ForegroundColor Yellow
    Write-Host "Using built-in agents only." -ForegroundColor Yellow
} else {
    try {
        $AgentsContent = Get-Content $AgentsFile -Raw | ConvertFrom-Json
        $AgentCount = $AgentsContent.agents.Count
        Write-Host "Loaded $AgentCount custom agents from agents.json" -ForegroundColor Green
    } catch {
        Write-Host "WARNING: agents.json is not valid JSON" -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "Direct tools: Read/Glob/Grep (2 max) | FORBIDDEN: Bash/Write/Edit" -ForegroundColor Yellow
Write-Host ""

# Read policy content
$PolicyContent = Get-Content $PolicyFile -Raw

# Build the append system prompt
$AppendPrompt = @"

======================================================================
AGENT-ONLY EXECUTION MODE ACTIVE
======================================================================

$PolicyContent
"@

# Build claude command arguments
$ClaudeArgs = @(
    "--append-system-prompt"
    $AppendPrompt
)

# Add any remaining arguments passed to this script
if ($RemainingArgs) {
    $ClaudeArgs += $RemainingArgs
}

Write-Host "Starting Claude in Agent-Only mode..." -ForegroundColor Green
Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# Execute claude
& claude @ClaudeArgs
exit $LASTEXITCODE
`;
}

/**
 * Generate Bash launcher
 */
export function generateBashLauncher() {
  return `#!/bin/bash
# ============================================================
# Claude Agent-Only Mode Launcher (Mac/Linux)
# ============================================================
#
# This script launches Claude in Agent-Only execution mode
# with policy enforcement via --append-system-prompt.
#
# Usage:
#   ./claude-agent-only.sh
#   ./claude-agent-only.sh --permission-mode acceptEdits
#
# Generated by: gtask claude-settings
# ============================================================

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$SCRIPT_DIR/.claude"
POLICY_FILE="$CLAUDE_DIR/AGENT_ONLY_POLICY.md"
AGENTS_FILE="$CLAUDE_DIR/agents.json"

# Banner
echo ""
echo "================================================"
echo "   CLAUDE - AGENT-ONLY EXECUTION MODE (STRICT)"
echo "================================================"
echo ""

# Validate required files exist
if [ ! -f "$POLICY_FILE" ]; then
    echo "ERROR: Policy file not found!"
    echo "Expected: $POLICY_FILE"
    echo ""
    echo "Run 'gtask claude-settings' to create it."
    exit 1
fi

if [ -f "$AGENTS_FILE" ]; then
    AGENT_COUNT=$(jq '.agents | length' "$AGENTS_FILE" 2>/dev/null || echo "0")
    echo "Loaded $AGENT_COUNT custom agents from agents.json"
else
    echo "WARNING: Agents file not found. Using built-in agents only."
fi

echo ""
echo "Direct tools: Read/Glob/Grep (2 max) | FORBIDDEN: Bash/Write/Edit"
echo ""

# Read policy content
POLICY_CONTENT=$(cat "$POLICY_FILE")

# Build the append system prompt
APPEND_PROMPT="
======================================================================
AGENT-ONLY EXECUTION MODE ACTIVE
======================================================================

$POLICY_CONTENT
"

echo "Starting Claude in Agent-Only mode..."
echo ""
echo "================================================"
echo ""

# Execute claude with appended prompt
claude --append-system-prompt "$APPEND_PROMPT" "$@"
`;
}
