/**
 * Agent policy and configuration generators
 */

/**
 * Generate AGENT_ONLY_POLICY.md content
 */
export function generateAgentOnlyPolicy() {
  return `# Agent Only Execution Policy (STRICT)

**ENFORCEMENT LEVEL: MANDATORY**

All substantive work (implementation, analysis, writing) MUST be delegated to agents via the Task tool.

---

## DEFAULT BEHAVIOR: Delegate via Task Tool

**Agents are the DEFAULT. Direct tools are the EXCEPTION.**

ALL substantive work MUST use Task tool with appropriate agent:
- Investigation/Analysis → \`Task(subagent_type="Explore")\`
- Implementation → \`Task(subagent_type="general-purpose")\` or custom agent
- Multi-step tasks → Task with specialist agent
- Code review/debugging → Task with appropriate agent

---

## Permitted Direct Tools (STRICTLY LIMITED)

| Tool | Call Limit | Permitted Purpose |
|------|------------|-------------------|
| **Read** | 2 calls max | Verify agent output, check single file |
| **Glob** | 2 calls max | Quick path existence check |
| **Grep** | 2 calls max | Single pattern search |
| **TodoWrite** | Unlimited | Task tracking and planning |
| **AskUserQuestion** | Unlimited | Clarifying with user |
| **Task** | Unlimited | Agent dispatch (REQUIRED) |

### FORBIDDEN Direct Tools

| Tool | Status | Alternative |
|------|--------|-------------|
| **Bash** | FORBIDDEN | Delegate to \`general-purpose\` or \`Explore\` agent |
| **Write** | FORBIDDEN | Delegate to appropriate agent |
| **Edit** | FORBIDDEN | Delegate to appropriate agent |
| **WebFetch** | FORBIDDEN | Delegate to agent |
| **WebSearch** | FORBIDDEN | Delegate to agent |

---

## Immediate Delegation Triggers

When user asks to do ANY of the following, spawn an agent IMMEDIATELY as your FIRST action:

| Trigger Word | Agent to Use |
|--------------|--------------|
| review | \`Explore\` |
| analyze | \`Explore\` |
| investigate | \`Explore\` |
| fix | \`general-purpose\` |
| implement | \`general-purpose\` |
| debug | \`general-purpose\` |
| research | \`Explore\` |
| find | \`Explore\` |

**Do NOT make direct tool calls first. Delegate IMMEDIATELY.**

---

## Violation Detection & Self-Correction

### You Are Violating This Policy If:

1. You make 3+ direct Read/Glob/Grep calls without delegating
2. You use Bash directly for ANY reason
3. You analyze code across multiple files without spawning an agent
4. You perform git operations directly instead of via agent
5. You investigate/debug without first spawning an agent

### Self-Correction Protocol:

If you catch yourself making too many direct calls:

\`\`\`
STOP - Policy violation detected
Delegating remaining work to agent...
→ Task(subagent_type="Explore", prompt="Continue investigation of...")
\`\`\`

---

## Agent Dispatch Protocol

Use Claude Code's Task tool to dispatch work:

\`\`\`
Task(
  subagent_type="<agent-type>",
  prompt="<detailed task description>",
  description="<3-5 word summary>"
)
\`\`\`

### Built-in Agent Types (ALWAYS AVAILABLE)

| Agent | Use For |
|-------|---------|
| \`general-purpose\` | Implementation, debugging, multi-step tasks |
| \`Explore\` | File search, codebase exploration, pattern finding |
| \`Plan\` | Architecture planning, implementation strategy |

---

*Generated by gtask claude-settings - ${new Date().toISOString()}*
`;
}

/**
 * Generate agents.json content
 */
export function generateAgentsJson() {
  const agents = {
    version: '1.0',
    agents: [
      {
        name: 'frontend_dev',
        scope: 'React, TypeScript, UI components, styling',
        when_to_use: 'Frontend implementation, component creation, UI fixes',
        when_not_to_use: 'Backend work, database operations',
        output_contract: {
          required_fields: ['files_modified', 'components_affected'],
          format: 'Concise summary with code snippets',
        },
      },
      {
        name: 'backend_dev',
        scope: 'API endpoints, Python services, database queries',
        when_to_use: 'Backend implementation, API creation, service logic',
        when_not_to_use: 'UI work, frontend components',
        output_contract: {
          required_fields: ['endpoints_modified', 'services_affected'],
          format: 'Concise summary with code snippets',
        },
      },
      {
        name: 'test_review',
        scope: 'Testing, code review, quality assurance',
        when_to_use: 'Writing tests, reviewing code, finding bugs',
        when_not_to_use: 'Feature implementation',
        output_contract: {
          required_fields: ['tests_added', 'issues_found'],
          format: 'Test results and recommendations',
        },
      },
      {
        name: 'docs_writer',
        scope: 'Documentation, README files, API docs',
        when_to_use: 'Writing documentation, updating README, API docs',
        when_not_to_use: 'Code implementation',
        output_contract: {
          required_fields: ['files_updated'],
          format: 'Documentation content',
        },
      },
    ],
  };

  return JSON.stringify(agents, null, 2);
}
