/**
 * Roadmap Executor - Status and Reporting
 *
 * Handles execution status retrieval, GitHub sync, and report generation.
 */

import { loadRoadmap } from '../roadmap-manager.js';
import { getRoadmapProgress } from '../phase-generator.js';
import { getNextAvailablePhases } from '../schema.js';
import { syncToGitHub } from '../github-integration.js';
import { loadExecutionState } from './state.js';

/**
 * Get execution status for a roadmap
 *
 * @param {string} roadmapSlug - Roadmap slug
 * @param {string} cwd - Current working directory
 * @returns {Object} Execution status
 */
export function getExecutionStatus(roadmapSlug, cwd = process.cwd()) {
  const roadmap = loadRoadmap(roadmapSlug, cwd);

  if (!roadmap) {
    return null;
  }

  const state = loadExecutionState(roadmapSlug, cwd);
  const progress = getRoadmapProgress(roadmapSlug, cwd);
  const nextPhases = getNextAvailablePhases(roadmap);

  return {
    roadmap: {
      id: roadmap.roadmap_id,
      title: roadmap.title,
      slug: roadmap.slug,
      status: roadmap.status,
    },
    execution: state ? {
      mode: state.mode,
      current_phase: state.current_phase,
      queue: state.queue,
      completed: state.completed_all_time,
      metrics: state.metrics,
    } : null,
    progress: progress ? {
      phases: progress.phases,
      totalTasks: progress.totalTasks,
      completedTasks: progress.completedTasks,
      percentage: progress.overallPercentage,
    } : null,
    nextAvailable: nextPhases.map(p => ({
      phase_id: p.phase_id,
      title: p.phase_title,
    })),
  };
}

/**
 * Sync roadmap execution status to GitHub
 *
 * @param {string} roadmapSlug - Roadmap slug
 * @param {string} cwd - Current working directory
 * @returns {Object} Sync result
 */
export async function syncExecution(roadmapSlug, cwd = process.cwd()) {
  const roadmap = loadRoadmap(roadmapSlug, cwd);

  if (!roadmap) {
    return {
      success: false,
      error: `Roadmap not found: ${roadmapSlug}`,
    };
  }

  if (!roadmap.metadata?.github_integrated) {
    return {
      success: false,
      error: 'Roadmap not integrated with GitHub',
    };
  }

  return await syncToGitHub(roadmap);
}

/**
 * Generate execution report
 *
 * @param {string} roadmapSlug - Roadmap slug
 * @param {string} cwd - Current working directory
 * @returns {string} Markdown report
 */
export function generateExecutionReport(roadmapSlug, cwd = process.cwd()) {
  const status = getExecutionStatus(roadmapSlug, cwd);

  if (!status) {
    return `# Execution Report\n\nRoadmap not found: ${roadmapSlug}`;
  }

  let report = `# Execution Report: ${status.roadmap.title}\n\n`;
  report += `**Generated:** ${new Date().toISOString()}\n\n`;

  report += `## Status\n\n`;
  report += `- **Roadmap Status:** ${status.roadmap.status}\n`;

  if (status.execution) {
    report += `- **Execution Mode:** ${status.execution.mode}\n`;
    report += `- **Current Phase:** ${status.execution.current_phase || 'None'}\n`;
    report += `- **Phases Completed:** ${status.execution.metrics.phases_completed_total}\n`;
    report += `- **Phases Remaining:** ${status.execution.metrics.phases_remaining}\n`;
  }

  report += `\n## Progress\n\n`;

  if (status.progress) {
    report += `**Overall:** ${status.progress.percentage}% (${status.progress.completedTasks}/${status.progress.totalTasks} tasks)\n\n`;

    report += `| Phase | Status | Progress |\n`;
    report += `|-------|--------|----------|\n`;

    for (const phase of status.progress.phases) {
      const statusIcon = phase.status === 'completed' ? '✅' :
                         phase.status === 'in_progress' ? '🔄' :
                         phase.status === 'blocked' ? '🚫' : '⬜';
      report += `| ${statusIcon} ${phase.title} | ${phase.status} | ${phase.percentage}% |\n`;
    }
  }

  if (status.nextAvailable.length > 0) {
    report += `\n## Next Available\n\n`;
    for (const phase of status.nextAvailable) {
      report += `- ${phase.phase_id}: ${phase.title}\n`;
    }
  }

  report += `\n---\n*Generated by CCASP Roadmap Executor*\n`;

  return report;
}
