/**
 * Generator Functions
 *
 * Template generators for various CCASP artifacts:
 * - Starter agents, skills, hooks
 * - Settings files
 * - Menu command
 * - Index and README files
 *
 * Extracted from init.js for maintainability.
 */

import { getVersion } from '../../utils.js';
import { AVAILABLE_COMMANDS } from './features.js';

/**
 * Generate menu command content
 * Creates the interactive ASCII menu slash command
 */
export function generateMenuCommand(projectName, installedCommands, installedAgents, installedSkills, installedHooks) {
  const date = new Date().toISOString().split('T')[0];

  // Build command table from installed commands
  const commandTable = installedCommands
    .map((name) => {
      const cmd = AVAILABLE_COMMANDS.find((c) => c.name === name);
      return cmd ? `| \`/${name}\` | ${cmd.category} | ${cmd.description} |` : null;
    })
    .filter(Boolean)
    .join('\n');

  // Build agent list
  const agentList =
    installedAgents.length > 0
      ? installedAgents.map((a) => `- **${a}** - Custom agent`).join('\n')
      : '- No agents installed yet';

  // Build skill list
  const skillList =
    installedSkills.length > 0
      ? installedSkills.map((s) => `- **/${s}** - Custom skill`).join('\n')
      : '- No skills installed yet';

  // Build hook list
  const hookList =
    installedHooks.length > 0
      ? installedHooks.map((h) => `- **${h}** - Active hook`).join('\n')
      : '- No hooks installed yet';

  return `---
description: Interactive project menu - Quick access to all commands, agents, skills, and tools
---

# ${projectName} - Interactive Menu

> Installed by Claude CLI Advanced Starter Pack v${getVersion()} on ${date}

## Quick Access Keys

Reply with a **single character** for quick navigation:

| Key | Action | Description |
|-----|--------|-------------|
| **1** | TOP TASK | Start #1 from Project Board |
| **2** | NEXT TASK | Pick next task |
| **3** | Commit | git status + staged commit |
| **4** | GitHub Board | /github-update |
| **5** | Roadmap | /create-roadmap or /roadmap-status |
| **M** | Deploy | /deploy-full |
| **O** | E2E Tests | /e2e-test |
| **T** | Task List | /create-task-list |
| **A** | Claude Audit | /claude-audit |
| **X** | Settings | /claude-settings |

## All Commands

| Command | Category | Description |
|---------|----------|-------------|
${commandTable}

## Agents

${agentList}

## Skills

${skillList}

## Active Hooks

${hookList}

---

*Generated by Claude CLI Advanced Starter Pack v${getVersion()} on ${date}*
`;
}

/**
 * Generate starter agent file
 */
export function generateStarterAgent(agentName) {
  return `---
description: ${agentName} agent - Add your description here
tools:
  - Read
  - Grep
  - Glob
  - Bash
---

# ${agentName} Agent

## Purpose

Describe what this agent does and when to use it.

## Capabilities

- List the agent's primary capabilities
- What tasks it can handle
- What domains it specializes in

## Usage

Invoke this agent with the Task tool:

\`\`\`
Task: "${agentName}"
Prompt: "Your task description here"
\`\`\`

## Instructions

When this agent is invoked:

1. Understand the task context
2. Use available tools to gather information
3. Execute the required actions
4. Report results clearly
`;
}

/**
 * Generate starter skill file
 */
export function generateStarterSkill(skillName) {
  return `---
description: ${skillName} skill - Add your description here
---

# ${skillName} Skill

## Overview

Describe what this skill provides and when to use it.

## Context

This skill has access to supporting documentation in the \`context/\` folder.

## Workflows

Step-by-step procedures are available in the \`workflows/\` folder.

## Usage

Invoke this skill by typing \`/${skillName}\` or referencing it with the Skill tool.

## Instructions

When this skill is invoked:

1. Load relevant context from the context folder
2. Follow applicable workflows
3. Apply domain expertise
4. Provide clear, actionable guidance
`;
}

/**
 * Generate starter hook file
 */
export function generateStarterHook(hookName, eventType = 'PreToolUse') {
  return `/**
 * ${hookName} Hook
 *
 * Event: ${eventType}
 * Description: Add your description here
 */

export default async function ${hookName.replace(/-/g, '_')}(context) {
  const { tool, input, session } = context;

  // Example: Log all tool usage
  console.log(\`[${hookName}] Tool: \${tool}, Input: \${JSON.stringify(input).slice(0, 100)}\`);

  // Return decision
  return {
    continue: true,  // Set to false to block the action
    // message: 'Optional message to show user',
    // modifiedInput: input,  // Optional: modify the input
  };
}
`;
}

/**
 * Generate CCASP update check hook (fallback if template not found)
 */
export function generateUpdateCheckHook() {
  return `/**
 * CCASP Update Check Hook
 *
 * Checks for npm updates when Claude Code starts.
 * Runs on first UserPromptSubmit per session, caches results for 1 hour.
 *
 * Event: UserPromptSubmit
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const PACKAGE_NAME = 'claude-cli-advanced-starter-pack';
const CACHE_DURATION = 60 * 60 * 1000;
const STATE_FILE = '.claude/config/ccasp-state.json';
const SESSION_MARKER = '.claude/config/.ccasp-session-checked';

function loadState() {
  const statePath = path.join(process.cwd(), STATE_FILE);
  if (fs.existsSync(statePath)) {
    try { return JSON.parse(fs.readFileSync(statePath, 'utf8')); } catch {}
  }
  return { lastCheckTimestamp: 0, updateAvailable: false, projectImplCompleted: false };
}

function saveState(state) {
  const statePath = path.join(process.cwd(), STATE_FILE);
  const stateDir = path.dirname(statePath);
  if (!fs.existsSync(stateDir)) fs.mkdirSync(stateDir, { recursive: true });
  fs.writeFileSync(statePath, JSON.stringify(state, null, 2), 'utf8');
}

function hasCheckedThisSession() {
  const markerPath = path.join(process.cwd(), SESSION_MARKER);
  if (fs.existsSync(markerPath)) {
    try {
      const timestamp = parseInt(fs.readFileSync(markerPath, 'utf8'), 10);
      if (Date.now() - timestamp < 4 * 60 * 60 * 1000) return true;
    } catch {}
  }
  return false;
}

function markSessionChecked() {
  const markerPath = path.join(process.cwd(), SESSION_MARKER);
  const markerDir = path.dirname(markerPath);
  if (!fs.existsSync(markerDir)) fs.mkdirSync(markerDir, { recursive: true });
  fs.writeFileSync(markerPath, Date.now().toString(), 'utf8');
}

function compareVersions(v1, v2) {
  if (!v1 || !v2) return 0;
  const p1 = v1.split('.').map(Number), p2 = v2.split('.').map(Number);
  for (let i = 0; i < Math.max(p1.length, p2.length); i++) {
    if ((p1[i] || 0) > (p2[i] || 0)) return 1;
    if ((p1[i] || 0) < (p2[i] || 0)) return -1;
  }
  return 0;
}

module.exports = async function ccaspUpdateCheck(context) {
  if (hasCheckedThisSession()) return { continue: true };
  markSessionChecked();

  const state = loadState();
  const now = Date.now();

  if (state.lastCheckTimestamp && (now - state.lastCheckTimestamp) < CACHE_DURATION) {
    return { continue: true };
  }

  try {
    const current = execSync('npm list -g ' + PACKAGE_NAME + ' --json 2>/dev/null', { encoding: 'utf8', timeout: 5000 });
    const currentVersion = JSON.parse(current).dependencies?.[PACKAGE_NAME]?.version;

    const latest = execSync('npm view ' + PACKAGE_NAME + ' version', { encoding: 'utf8', timeout: 10000 }).trim();

    state.lastCheckTimestamp = now;
    state.currentVersion = currentVersion;
    state.latestVersion = latest;
    state.updateAvailable = compareVersions(latest, currentVersion) > 0;
    saveState(state);
  } catch {}

  return { continue: true };
};
`;
}

/**
 * Generate settings.json with CCASP update check hook and usage tracking
 */
export function generateSettingsJson(projectName) {
  return JSON.stringify(
    {
      $schema: 'https://json.schemastore.org/claude-code-settings.json',
      permissions: {
        allow: [],
        deny: [],
      },
      hooks: {
        UserPromptSubmit: [
          {
            matcher: '',
            hooks: [
              {
                type: 'command',
                command: 'node .claude/hooks/ccasp-update-check.js',
              },
            ],
          },
        ],
        PostToolUse: [
          {
            matcher: 'Skill|Read',
            hooks: [
              {
                type: 'command',
                command: 'node .claude/hooks/usage-tracking.js',
              },
            ],
          },
        ],
      },
    },
    null,
    2
  );
}

/**
 * Generate settings.local.json
 */
export function generateSettingsLocalJson() {
  return JSON.stringify(
    {
      $schema: 'https://json.schemastore.org/claude-code-settings.json',
      permissions: {
        allow: [],
        deny: [],
      },
      hooks: {},
    },
    null,
    2
  );
}

/**
 * Generate INDEX.md file
 */
export function generateIndexFile(commands, projectName) {
  const date = new Date().toISOString().split('T')[0];

  let content = `# ${projectName} - Slash Commands

> Installed by Claude CLI Advanced Starter Pack v${getVersion()} on ${date}

## Quick Start

Type \`/menu\` to open the interactive project menu.

## Available Commands

| Command | Description |
|---------|-------------|
`;

  for (const cmdName of commands) {
    const cmd = AVAILABLE_COMMANDS.find((c) => c.name === cmdName);
    if (cmd) {
      content += `| \`/${cmdName}\` | ${cmd.description} |\n`;
    }
  }

  content += `
## Project Structure

\`\`\`
.claude/
├── commands/     # Slash commands (you are here)
├── agents/       # Custom agents
├── skills/       # Skill packages
├── hooks/        # Enforcement hooks
├── docs/         # Documentation
├── settings.json
└── settings.local.json
\`\`\`

## Reinstall/Update

\`\`\`bash
npx claude-cli-advanced-starter-pack init --force
\`\`\`

## Learn More

- [Claude CLI Advanced Starter Pack on npm](https://www.npmjs.com/package/claude-cli-advanced-starter-pack)
- [GitHub Repository](https://github.com/evan043/claude-cli-advanced-starter-pack)
`;

  return content;
}

/**
 * Generate README.md file
 */
export function generateReadmeFile(commands, projectName) {
  const categories = {};

  for (const cmdName of commands) {
    const cmd = AVAILABLE_COMMANDS.find((c) => c.name === cmdName);
    if (cmd) {
      if (!categories[cmd.category]) {
        categories[cmd.category] = [];
      }
      categories[cmd.category].push(cmd);
    }
  }

  let content = `# ${projectName} - Slash Commands

This folder contains Claude Code CLI slash commands installed by Claude CLI Advanced Starter Pack.

## Interactive Menu

Type \`/menu\` to access the interactive ASCII menu with quick access to all commands.

## Commands by Category

`;

  for (const [category, cmds] of Object.entries(categories)) {
    content += `### ${category}\n\n`;
    for (const cmd of cmds) {
      content += `- **/${cmd.name}** - ${cmd.description}\n`;
    }
    content += '\n';
  }

  content += `## How Commands Work

Each \`.md\` file in this directory is a slash command. When you type \`/command-name\` in Claude Code CLI, Claude reads the corresponding \`.md\` file and follows the instructions.

### Command Structure

\`\`\`markdown
---
description: Brief description shown in command list
options:
  - label: "Option 1"
    description: "What this option does"
---

# Command Title

Instructions for Claude to follow when this command is invoked.
\`\`\`

## Creating Custom Commands

1. Create a new \`.md\` file in this directory
2. Add YAML frontmatter with description
3. Write instructions for Claude to follow
4. The command name is the filename (without .md)

## Reinstalling

To reinstall or update commands:

\`\`\`bash
npx claude-cli-advanced-starter-pack init --force
\`\`\`
`;

  return content;
}
