/**
 * Orchestrator Planning - Exploration Documentation
 * Creates exploration documentation files for roadmaps
 */

import fs from 'fs';
import path from 'path';

/**
 * Create exploration documentation files for a roadmap
 */
export async function createExplorationDocs(explorationDir, roadmapSpec, roadmapSlug) {
  const now = new Date().toISOString();

  // EXPLORATION_SUMMARY.md
  const summary = `# Exploration Summary: ${roadmapSpec.title}

## Overview
- **Roadmap:** ${roadmapSlug}
- **Created:** ${now}
- **Status:** Initial exploration complete

## Scope
${roadmapSpec.description || 'N/A'}

## Phase Count
${roadmapSpec.phases?.length || 0} phases identified

## Task Count
${roadmapSpec.phases?.reduce((sum, p) => sum + (p.tasks?.length || 0), 0) || 0} tasks total

---
_Generated by Vision Orchestrator_
`;
  fs.writeFileSync(path.join(explorationDir, 'EXPLORATION_SUMMARY.md'), summary, 'utf8');

  // CODE_SNIPPETS.md
  const snippets = `# Code Snippets: ${roadmapSpec.title}

## Relevant Code Patterns

_To be populated during execution phase with relevant code snippets._

---
_Generated by Vision Orchestrator_
`;
  fs.writeFileSync(path.join(explorationDir, 'CODE_SNIPPETS.md'), snippets, 'utf8');

  // REFERENCE_FILES.md
  const refFiles = `# Reference Files: ${roadmapSpec.title}

## Key Files to Modify

_To be populated during execution phase with file paths and line numbers._

---
_Generated by Vision Orchestrator_
`;
  fs.writeFileSync(path.join(explorationDir, 'REFERENCE_FILES.md'), refFiles, 'utf8');

  // AGENT_DELEGATION.md
  const agentDelegation = `# Agent Delegation: ${roadmapSpec.title}

## Task Assignments

${roadmapSpec.phases.map((phase, i) => `
### Phase ${i + 1}: ${phase.title}
${phase.tasks.map((task, j) => `- Task ${j + 1}: ${task.name || task} → [Agent TBD]`).join('\n')}
`).join('\n')}

---
_Generated by Vision Orchestrator_
`;
  fs.writeFileSync(path.join(explorationDir, 'AGENT_DELEGATION.md'), agentDelegation, 'utf8');

  // PHASE_BREAKDOWN.md
  const phaseBreakdown = `# Phase Breakdown: ${roadmapSpec.title}

${roadmapSpec.phases.map((phase, i) => `
## Phase ${i + 1}: ${phase.title}

### Tasks
${phase.tasks.map((task, j) => `${j + 1}. **${task.name || task}**
   - Description: ${task.description || 'N/A'}
   - Status: Not started
`).join('\n')}
`).join('\n')}

---
_Generated by Vision Orchestrator_
`;
  fs.writeFileSync(path.join(explorationDir, 'PHASE_BREAKDOWN.md'), phaseBreakdown, 'utf8');

  // findings.json
  const findings = {
    roadmap_slug: roadmapSlug,
    title: roadmapSpec.title,
    created: now,
    phases: roadmapSpec.phases.map((phase, i) => ({
      phase_index: i,
      title: phase.title,
      task_count: phase.tasks?.length || 0,
      tasks: phase.tasks.map((task, j) => ({
        task_index: j,
        name: task.name || task,
        description: task.description || ''
      }))
    })),
    total_tasks: roadmapSpec.phases?.reduce((sum, p) => sum + (p.tasks?.length || 0), 0) || 0
  };
  fs.writeFileSync(path.join(explorationDir, 'findings.json'), JSON.stringify(findings, null, 2), 'utf8');
}
